# Generated by Django 2.2.7 on 2019-11-19 00:24

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='updated time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='deleted marker')),
                ('name', models.CharField(max_length=20, verbose_name='goods_spu_name')),
                ('detail', tinymce.models.HTMLField(blank=True, verbose_name='goods_spu_detail')),
            ],
            options={
                'verbose_name': 'goods_spu',
                'verbose_name_plural': 'goods_spu',
                'db_table': 'df_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='updated time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='deleted marker')),
                ('name', models.CharField(max_length=20, verbose_name='good_name')),
                ('desc', models.CharField(max_length=256, verbose_name='good_description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='good_price')),
                ('unite', models.CharField(max_length=20, verbose_name='good_unit')),
                ('image', models.ImageField(upload_to='goods', verbose_name='good_image')),
                ('stock', models.IntegerField(default=1, verbose_name='good_stock')),
                ('sales', models.IntegerField(default=0, verbose_name='good_sales')),
                ('status', models.SmallIntegerField(choices=[(0, 'not_on_sell'), (1, 'on_sell')], default=1, verbose_name='good_status')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_detail', to='goods.Goods', verbose_name='good_spu')),
            ],
            options={
                'verbose_name': 'good',
                'verbose_name_plural': 'good',
                'db_table': 'df_goods_sku',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='updated time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='deleted marker')),
                ('name', models.CharField(max_length=20, verbose_name='type_name')),
                ('logo', models.CharField(max_length=20, verbose_name='logo')),
                ('image', models.ImageField(upload_to='type', verbose_name='type_image')),
            ],
            options={
                'verbose_name': 'good_types',
                'verbose_name_plural': 'good_types',
                'db_table': 'df_goods_type',
            },
        ),
        migrations.CreateModel(
            name='IndexPromotionBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='updated time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='deleted marker')),
                ('name', models.CharField(max_length=20, verbose_name='promotion_name')),
                ('url', models.CharField(max_length=256, verbose_name='promotion_url')),
                ('image', models.ImageField(upload_to='banner', verbose_name='promotion_image')),
                ('index', models.SmallIntegerField(default=0, verbose_name='display_sequence')),
            ],
            options={
                'verbose_name': 'index_promotion',
                'verbose_name_plural': 'index_promotion',
                'db_table': 'df_index_promotion',
            },
        ),
        migrations.CreateModel(
            name='IndexTypeGoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='updated time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='deleted marker')),
                ('display_type', models.SmallIntegerField(choices=[(0, 'title'), (1, 'image')], default=1, verbose_name='display_choice')),
                ('index', models.SmallIntegerField(default=0, verbose_name='display_sequence')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_type_goods', to='goods.GoodsType', verbose_name='type')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_type_goods', to='goods.GoodsSKU', verbose_name='good')),
            ],
            options={
                'verbose_name': 'index_type_goods',
                'verbose_name_plural': 'index_type_goods',
                'db_table': 'df_index_type_goods',
            },
        ),
        migrations.CreateModel(
            name='IndexGoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='updated time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='deleted marker')),
                ('image', models.ImageField(upload_to='banner', verbose_name='image')),
                ('index', models.SmallIntegerField(default=0, verbose_name='display_sequence')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_goods', to='goods.GoodsSKU', verbose_name='good')),
            ],
            options={
                'verbose_name': 'index_goods',
                'verbose_name_plural': 'index_goods',
                'db_table': 'df_index_banner',
            },
        ),
        migrations.AddField(
            model_name='goodssku',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_detail', to='goods.GoodsType', verbose_name='good_type'),
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='updated time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='deleted marker')),
                ('image', models.ImageField(upload_to='goods', verbose_name='image_path')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_image', to='goods.GoodsSKU', verbose_name='good')),
            ],
            options={
                'verbose_name': 'good_image',
                'verbose_name_plural': 'good_image',
                'db_table': 'df_goods_image',
            },
        ),
    ]
