# Generated by Django 2.2.7 on 2019-11-19 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_image', to='goods.GoodsSKU', verbose_name='good'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_sku', to='goods.Goods', verbose_name='good_spu'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_sku', to='goods.GoodsType', verbose_name='good_type'),
        ),
    ]
