# Generated by Django 2.2.7 on 2019-11-30 22:26

import apps.goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191118_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(upload_to=apps.goods.models.upload_image_path, verbose_name='image_path'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='image',
            field=models.ImageField(upload_to=apps.goods.models.upload_image_path, verbose_name='good_image'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='image',
            field=models.ImageField(upload_to=apps.goods.models.upload_image_path, verbose_name='type_image'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='image',
            field=models.ImageField(upload_to=apps.goods.models.upload_image_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='image',
            field=models.ImageField(upload_to=apps.goods.models.upload_image_path, verbose_name='promotion_image'),
        ),
    ]
